import Swiper from 'swiper';
import 'swiper/css';
import './js/components/header';
import './js/components/footer';
import './js/components/form';
import './js/components/modal';
import './js/pages/home';
import './js/pages/projects';
// import './js/utils/map';
import './index.scss';
